### ISSUE TITLE
Error Response with Render

### ISSUE THREAD

**Issue by KaranAhlawat** [prestancedesign/inertia-clojure#4]
Is it possible to send a 404 response AND render an Page? I'd like to render a custom 404 page whenever the user goes to an undefined route. And I'd like to not have to setup stuff specifically for this, apart from my Inertia client.

I could not find any examples, so I'm creating an issue here.

**Comment by prestancedesign** [comment]
Which routing lib do you use?

Here you can find an example how it's managed for the PingCRM demo with Reitit: https://github.com/prestancedesign/pingcrm-clojure/blob/88317da68a4fb7073dd1b936ab3c8749eeeb7036/src/clj/pingcrm/router.clj#L96-L97
And the custom 404 page: https://github.com/prestancedesign/pingcrm-clojure/blob/9505c33c27ac736e18aae6a0e97acd099c1fb3f0/src/clj/pingcrm/templates/404.clj

The live demo 404 page: https://inertia.prestance-design.com/jkjk

LMK, if it helps.

**Comment by KaranAhlawat** [comment]
I'm using reitit-ring as my routing lib.

I tried what is used in ping-crm, but the problem is I have my 404 template as a Svelte component. Hence it requires the use of inertia/render function to tell Inertia to display it. That I haven't been able to figure out how to use with the create-default-handler.

**Comment by prestancedesign** [comment]
OK, so you use Clojure for the back end and Svelte for the front end, right?

**Comment by KaranAhlawat** [comment]
Yes, that would be correct. I can share the link of the repo if that would be helpful.

https://git.sr.ht/~korven/svelte-inertia

**Comment by prestancedesign** [comment]
Does the 404 page have to be dynamic?

If not, I would use a static template like `resources/404.html` and set `create-default-handler` to point to this file in line 39 of your `server.clj` file: https://git.sr.ht/~korven/svelte-inertia/tree/master/item/server/inert/server.clj#L39:
```
(ring/create-default-handler
    {:not-found (constantly
                 {:status 404
                  :body (-> "404.html" io/resource io/file)})})
```

Does this solution suit for you?

**Comment by KaranAhlawat** [comment]
That would work, in theory yes. But I'd rather have a Svelte component, just so I can integrate it with the global layout, just like other pages. Makes navigation easier. If there is no other way though, I suppose nothing to be done about it.

**Comment by prestancedesign** [comment]
FYI, I just released a new version which keep now the http status code specified in the handler response.

So you can now update your `default-handler` with:
```
(defn default-handler
  "Render the Default component"
  [_]
  (-> (inertia/render :Default {:status 404})
      (assoc :status 404)))

```

Please, let me know if this answers your question.

**Comment by KaranAhlawat** [comment]
That works perfectly! I really missed something so simple. Thanks for your time, it's a pleasure working with this library. Will be closing this now.

**Comment by prestancedesign** [comment]
OK perfect, you're welcome!

> I really missed something so simple. 

A new release with some modifications was necessary to handle correctly and keep the status code so thanks for pointing it out: https://github.com/prestancedesign/inertia-clojure/commit/6b1bb458ebfbc34710dd628dd8b8ce788309f096

Do not hesitate to do a PR to add your repo on fullstack project example readme section when finished.
